# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gator"
  s.version = "0.0.25.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dominic Graefen"]
  s.date = "2011-10-31"
  s.description = "gator - the friendly code-generator"
  s.email = "dominic.graefen@gmail.com"
  s.executables = ["gator"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gator",
    "gator.gemspec",
    "lib/gator.rb",
    "lib/gator/core.rb",
    "lib/gator/core/application/application.rb",
    "lib/gator/core/application/application_configuration.rb",
    "lib/gator/core/command/act_as_command.rb",
    "lib/gator/core/command/act_as_command_collection.rb",
    "lib/gator/core/command/command.rb",
    "lib/gator/core/command/task.rb",
    "lib/gator/core/configuration/act_as_configuration.rb",
    "lib/gator/core/configuration/configuration.rb",
    "lib/gator/core/io/paths.rb",
    "lib/gator/core/io/project_file_locator.rb",
    "lib/gator/core/io/ruby_file_loader.rb",
    "lib/gator/core/io/sandbox.rb",
    "lib/gator/core/project/layout.rb",
    "lib/gator/core/project/project.rb",
    "lib/gator/plugins/generators.rb",
    "lib/gator/plugins/generators/act_as_template_generator.rb",
    "lib/gator/plugins/generators/generate_command.rb",
    "lib/gator/plugins/generators/generator.rb",
    "lib/gator/plugins/scaffolding.rb",
    "lib/gator/plugins/scaffolding/scaffold_command.rb",
    "lib/gator/plugins/scaffolding/scaffolding_file_utils.rb",
    "rake/jeweler.rb",
    "rake/jeweler_prerelease_tasks.rb",
    "rake/pre_release_gemspec.rb",
    "rake/pre_release_to_git.rb",
    "spec/core/application/application_configuration_spec.rb",
    "spec/core/application/application_spec.rb",
    "spec/core/command/command_spec.rb",
    "spec/core/command/task_spec.rb",
    "spec/core/configuration/configuration_spec.rb",
    "spec/core/io/paths_spec.rb",
    "spec/core/io/sandbox_spec.rb",
    "spec/core/project/layout_spec.rb",
    "spec/core/project/project_spec.rb",
    "spec/fixtures/empty_gator_project/gator.rb",
    "spec/fixtures/no_gator_file/.empty_directory",
    "spec/plugins/scaffolding/scaffold_command_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/devboy/gator"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "gator - the friendly code-generator"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.14.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<ci_reporter>, ["~> 1.6.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-rcov>, [">= 0"])
    else
      s.add_dependency(%q<thor>, ["~> 0.14.6"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<ci_reporter>, ["~> 1.6.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.14.6"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<ci_reporter>, ["~> 1.6.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-rcov>, [">= 0"])
  end
end

