require File.dirname(__FILE__) + '/core/cli'
require File.dirname(__FILE__) + '/core/command'
require File.dirname(__FILE__) + '/core/plugin'
require File.dirname(__FILE__) + '/core/configuration'
require File.dirname(__FILE__) + '/core/project'