require File.dirname(__FILE__) + '/gator/config'
require File.dirname(__FILE__) + '/gator/project'
require File.dirname(__FILE__) + '/gator/util'
require File.dirname(__FILE__) + '/gator/command'
require File.dirname(__FILE__) + '/gator/task'
require File.dirname(__FILE__) + '/gator/generators'
require File.dirname(__FILE__) + '/gator/runner'
require File.dirname(__FILE__) + '/gator/commands'