require File.dirname(__FILE__) + '/gator/config'
require File.dirname(__FILE__) + '/gator/util'
require File.dirname(__FILE__) + '/gator/runner'
require File.dirname(__FILE__) + '/gator/commands/command'
require File.dirname(__FILE__) + '/gator/commands/project_command'